#!/usr/bin/env npx tsx
/**
 * Hive Setup Wizard — interactive CLI to configure a new Hive instance.
 *
 * Saves progress after each section so you can quit and resume.
 * On resume, completed sections are detected and skipped (with option to redo).
 *
 * Usage:
 *   npm run setup
 *   npx tsx setup/setup-wizard.ts
 */

import { createInterface } from "node:readline";
import { readFileSync, writeFileSync, existsSync, readdirSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { resolve, join } from "node:path";
import { stringify as toYaml, parse as parseYaml } from "yaml";
import { MongoClient } from "mongodb";
import { render as renderTemplate } from "./template-renderer.js";

// Resolved per-invocation inside runWizard(). The module-level defaults
// would be wrong in npm-bundled mode (where `../..` from this file is not
// the repo root), so start empty and assert they are set before use.
const DEV_ROOT = resolve(import.meta.dirname, "../..");
let ENV_PATH = "";
let HIVE_YAML_PATH = "";

const rl = createInterface({ input: process.stdin, output: process.stdout });

function ask(question: string, defaultVal = ""): Promise<string> {
  const prompt = defaultVal ? `${question} [${defaultVal}]: ` : `${question}: `;
  return new Promise((resolve) => {
    rl.question(prompt, (answer) => {
      resolve(answer.trim() || defaultVal);
    });
  });
}

async function confirm(question: string, defaultYes = true): Promise<boolean> {
  const hint = defaultYes ? "Y/n" : "y/N";
  const answer = await ask(`${question} (${hint})`, defaultYes ? "y" : "n");
  return answer.toLowerCase().startsWith("y");
}

function banner() {
  console.log("");
  console.log("╔══════════════════════════════════════════════╗");
  console.log("║            Hive Setup Wizard                 ║");
  console.log("║   Multi-Agent Slack Orchestration Framework  ║");
  console.log("╚══════════════════════════════════════════════╝");
  console.log("");
}

function section(title: string) {
  console.log("");
  console.log(`── ${title} ${"─".repeat(Math.max(0, 44 - title.length))}`);
  console.log("");
}

// ── Env file helpers ───────────────────────────────────────────────

function loadEnv(): Record<string, string> {
  if (!existsSync(ENV_PATH)) return {};
  const env: Record<string, string> = {};
  for (const line of readFileSync(ENV_PATH, "utf-8").split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq);
    const val = trimmed.slice(eq + 1);
    env[key] = val;
  }
  return env;
}

function saveEnv(env: Record<string, string>) {
  const lines: string[] = [
    "# Hive environment — generated by setup wizard",
    "# Secrets and API keys. Do not commit this file.",
    "",
  ];

  const groups: Array<{ header: string; keys: string[] }> = [
    { header: "# Slack", keys: ["SLACK_APP_TOKEN", "SLACK_BOT_TOKEN", "SLACK_MCP_TOKEN"] },
    { header: "# Anthropic", keys: ["ANTHROPIC_API_KEY"] },
    { header: "# SMS (Quo/OpenPhone)", keys: ["QUO_API_KEY", "QUO_PHONE_NUMBER_ID"] },
    { header: "# Google", keys: ["GOOGLE_ACCOUNT"] },
    { header: "# Project Management", keys: ["LINEAR_API_KEY", "CLICKUP_API_TOKEN"] },
    { header: "# External Communications", keys: ["EXTERNAL_COMMS_ENABLED"] },
  ];

  const written = new Set<string>();
  for (const group of groups) {
    const groupLines: string[] = [];
    for (const key of group.keys) {
      written.add(key);
      const val = env[key];
      if (val) {
        groupLines.push(`${key}=${val}`);
      } else {
        groupLines.push(`# ${key}=`);
      }
    }
    if (groupLines.some((l) => !l.startsWith("#"))) {
      lines.push(group.header);
      lines.push(...groupLines);
      lines.push("");
    }
  }

  // Write any extra keys not in the groups
  for (const [key, val] of Object.entries(env)) {
    if (!written.has(key) && val) {
      lines.push(`${key}=${val}`);
    }
  }

  writeFileSync(ENV_PATH, lines.join("\n") + "\n");
}

// ── Hive yaml helpers ──────────────────────────────────────────────

function loadHiveYaml(): Record<string, any> {
  if (!existsSync(HIVE_YAML_PATH)) return {};
  return parseYaml(readFileSync(HIVE_YAML_PATH, "utf-8")) ?? {};
}

function saveHiveYaml(config: Record<string, any>) {
  writeFileSync(HIVE_YAML_PATH, toYaml(config));
}

// ── Section detection ──────────────────────────────────────────────

function isBusinessDone(hive: Record<string, any>): boolean {
  return !!(hive.business?.name && hive.business?.owner?.name);
}

function isSlackDone(env: Record<string, string>): boolean {
  return !!(env.SLACK_APP_TOKEN && env.SLACK_BOT_TOKEN);
}

async function isAgentDone(): Promise<boolean> {
  try {
    const client = new MongoClient(process.env.MONGODB_URI ?? "mongodb://localhost:27017");
    await client.connect();
    const db = client.db(process.env.MONGODB_DB ?? "hive");
    const agent = await db.collection("agent_definitions").findOne({ _id: "chief-of-staff" as any });
    await client.close();
    return !!agent;
  } catch {
    return false;
  }
}

function isBuildDone(targetDir: string): boolean {
  if (existsSync(resolve(import.meta.dirname, "..", "pkg", "server.min.js"))) return true;
  return existsSync(resolve(targetDir, "dist", "index.js"));
}

// ── Main ───────────────────────────────────────────────────────────

export async function runWizard(
  targetDir: string = DEV_ROOT,
  templatesDir: string = resolve(DEV_ROOT, "setup", "templates"),
): Promise<void> {
  // Update module-level paths for the target directory
  ENV_PATH = join(targetDir, ".env");
  HIVE_YAML_PATH = join(targetDir, "hive.yaml");

  banner();

  const env = loadEnv();
  const hive = loadHiveYaml();

  // Check for resumed session
  const completedSections: string[] = [];
  if (isBusinessDone(hive)) completedSections.push("Business info");
  if (isSlackDone(env)) completedSections.push("Slack");
  if (await isAgentDone()) completedSections.push("Agent setup");
  if (isBuildDone(targetDir)) completedSections.push("Build");

  if (completedSections.length > 0) {
    console.log("Resuming setup. Already completed:");
    for (const s of completedSections) {
      console.log(`  ✓ ${s}`);
    }
    console.log("");
  } else {
    console.log("This wizard will configure Hive for your business.");
    console.log("Progress is saved after each section — you can quit and resume anytime.");
    console.log("");
    await ask("Press Enter to begin...");
  }

  // ── 1. Business Info ──────────────────────────────────────────────
  if (isBusinessDone(hive)) {
    console.log(`Business: ${hive.business.name} (${hive.business.owner.name}, ${hive.business.owner.role})`);
    const redo = await confirm("Redo business info?", false);
    if (!redo) {
      console.log("  ✓ Skipped");
    } else {
      await doBusiness(hive);
    }
  } else {
    await doBusiness(hive);
  }

  // ── 2. Slack ──────────────────────────────────────────────────────
  if (isSlackDone(env)) {
    console.log(`Slack: ✓ tokens configured`);
    const redo = await confirm("Redo Slack setup?", false);
    if (!redo) {
      console.log("  ✓ Skipped");
    } else {
      await doSlack(env);
    }
  } else {
    await doSlack(env);
  }

  // ── 3. Anthropic ──────────────────────────────────────────────────
  section("Anthropic");

  if (env.ANTHROPIC_API_KEY) {
    console.log("Anthropic API key: ✓ configured");
    const redo = await confirm("Change it?", false);
    if (redo) {
      await doAnthropic(env);
    } else {
      console.log("  ✓ Skipped");
    }
  } else {
    console.log("Your Claude CLI session is already authenticated — Hive's Agent SDK");
    console.log("will use that automatically. No API key needed.");
    console.log("");
    const wantKey = await confirm("Use a separate API key instead?", false);
    if (wantKey) {
      await doAnthropic(env);
    } else {
      console.log("  ✓ Using existing Claude authentication");
      saveEnv(env);
    }
  }

  // ── 4. Optional Integrations ──────────────────────────────────────
  section("Optional Integrations");

  console.log("These can be added later. Press Enter to skip any.\n");

  // SMS via Quo
  const wantQuo = await confirm("Enable SMS via Quo (OpenPhone)?", false);
  if (wantQuo) {
    console.log("Get your API key from: Quo workspace settings → API tab");
    env.QUO_API_KEY = await ask("Quo API Key", env.QUO_API_KEY || "");
    env.QUO_PHONE_NUMBER_ID = await ask("Default Phone Number ID (PNxxx)", env.QUO_PHONE_NUMBER_ID || "");

    const smsLines: Array<{ id: string; label: string; number: string; slackChannel: string }> = [];
    const quoLines: Record<string, { id: string; number: string; label: string }> = {};

    const addLines = await confirm("Configure named phone lines?", false);
    if (addLines) {
      let more = true;
      while (more) {
        const lineName = await ask("Line name (e.g. main, personal)");
        const lineId = await ask("Phone Number ID (PNxxx)");
        const lineNumber = await ask("Phone number (e.g. (555) 123-4567)");
        const lineLabel = await ask("Label (e.g. Jane's Line)");
        const lineChannel = await ask("Slack channel for incoming SMS", `sms-${lineName}`);

        quoLines[lineName] = { id: lineId, number: lineNumber, label: lineLabel };
        smsLines.push({ id: lineId, label: lineLabel, number: lineNumber, slackChannel: lineChannel });

        more = await confirm("Add another line?", false);
      }
    }

    if (smsLines.length > 0) hive.sms = { lines: smsLines };
    if (Object.keys(quoLines).length > 0) hive.quo = { lines: quoLines };
  }

  // Google
  const wantGoogle = await confirm("Enable Google Gmail/Calendar integration?", false);
  if (wantGoogle) {
    // Check if gog is installed
    let gogInstalled = false;
    try {
      execFileSync("which", ["gog"], { stdio: "pipe" });
      gogInstalled = true;
      console.log("  ✓ gog CLI found");
    } catch {
      console.log("  gog CLI not found. Installing via Homebrew...");
      try {
        execFileSync("brew", ["install", "gog"], { stdio: "inherit" });
        gogInstalled = true;
        console.log("  ✓ gog CLI installed");
      } catch {
        console.log("  ⚠ Failed to install gog. Install manually: brew install gog");
      }
    }

    if (gogInstalled) {
      // Check existing accounts
      try {
        const authList = execFileSync("gog", ["auth", "list"], { encoding: "utf-8", stdio: "pipe" }).trim();
        if (authList && !authList.includes("no accounts")) {
          console.log("\n  Authenticated accounts:");
          console.log(`  ${authList.replace(/\n/g, "\n  ")}`);
        }
      } catch {}

      console.log("");
      const addAccount = await confirm("Authenticate a Google account now?", true);
      if (addAccount) {
        let addMore = true;
        while (addMore) {
          const email = await ask("Google account email");
          console.log(`\n  Opening browser for ${email}...`);
          console.log("  Complete the OAuth flow in your browser, then come back here.\n");
          try {
            execFileSync("gog", ["auth", "add", email], { stdio: "inherit" });
            console.log(`  ✓ ${email} authenticated`);
          } catch {
            console.log(`  ⚠ Authentication failed for ${email}. You can retry later: gog auth add ${email}`);
          }
          addMore = await confirm("Authenticate another Google account?", false);
        }
      }

      // Set primary account
      env.GOOGLE_ACCOUNT = await ask("Primary Google account for Hive", env.GOOGLE_ACCOUNT || "");

      // Verify it works
      if (env.GOOGLE_ACCOUNT) {
        try {
          execFileSync(
            "gog",
            ["gmail", "search", "is:unread", "-a", env.GOOGLE_ACCOUNT, "--json", "--results-only", "--no-input"],
            { encoding: "utf-8", timeout: 15_000 },
          );
          console.log(`  ✓ Gmail access verified for ${env.GOOGLE_ACCOUNT}`);
        } catch {
          console.log(`  ⚠ Could not verify Gmail access — check authentication later`);
        }
      }
    }
  }

  // Project Management
  const wantPm = await confirm("Enable project management integration?", false);
  if (wantPm) {
    const pmChoice = await ask("Which system? (linear / clickup)", "");
    if (pmChoice.toLowerCase().startsWith("l")) {
      env.LINEAR_API_KEY = await ask("Linear API Key", env.LINEAR_API_KEY || "");
      console.log("  Get it from: Linear → Settings → API → Personal API Keys");
    } else if (pmChoice.toLowerCase().startsWith("c")) {
      env.CLICKUP_API_TOKEN = await ask("ClickUp API Token", env.CLICKUP_API_TOKEN || "");
      console.log("  Get it from: ClickUp → Settings → Apps → API Token");
    } else {
      console.log("  Skipped — you can configure this in .env later.");
    }
  }

  // Save after integrations
  saveEnv(env);
  saveHiveYaml(hive);
  console.log("\n  ✓ Configuration saved (.env + hive.yaml)");

  // ── 4.5 Plugins ─────────────────────────────────────────────────
  section("Plugins");

  const pluginsDir = join(targetDir, "plugins");
  if (existsSync(pluginsDir)) {
    const available = readdirSync(pluginsDir).filter((d) => {
      return existsSync(join(pluginsDir, d, "plugin.yaml"));
    });

    if (available.length > 0) {
      console.log("Available plugins:\n");
      for (const p of available) {
        const manifest = parseYaml(readFileSync(join(pluginsDir, p, "plugin.yaml"), "utf-8"));
        console.log(`  ${p} — ${manifest.description ?? "(no description)"}`);
      }
      console.log("");

      const current = (hive.plugins ?? []).join(", ") || "none";
      const selected = await ask("Which plugins to enable? (comma-separated, or 'none')", current);
      if (selected.toLowerCase() !== "none") {
        hive.plugins = selected
          .split(",")
          .map((s: string) => s.trim())
          .filter(Boolean);
      } else {
        hive.plugins = [];
      }
    } else {
      console.log("No plugins found in plugins/ directory.");
      hive.plugins = [];
    }
  } else {
    console.log("No plugins/ directory found.");
    hive.plugins = [];
  }

  saveHiveYaml(hive);

  // ── 5. Agent Setup ────────────────────────────────────────────────
  if (await isAgentDone()) {
    console.log("\nChief of Staff agent: ✓ already set up");
    const redo = await confirm("Regenerate agent from template?", false);
    if (redo) {
      await doAgent(hive);
    } else {
      console.log("  ✓ Skipped");
    }
  } else {
    await doAgent(hive);
  }

  // ── 6. Constitution ──────────────────────────────────────────────
  await doConstitution(hive);

  // ── 7. Seed Memory to MongoDB ─────────────────────────────────────
  section("Memory (MongoDB)");
  await doMemory(hive, templatesDir);

  // ── 8. Build ──────────────────────────────────────────────────────
  section("Build");

  if (isBuildDone(targetDir)) {
    console.log("Build output exists.");
    const rebuild = await confirm("Rebuild?", true);
    if (!rebuild) {
      console.log("  ✓ Skipped");
    } else {
      await doBuild();
    }
  } else {
    await doBuild();
  }

  // ── 9. Deploy Clone ──────────────────────────────────────────────
  section("Deploy");

  const deployDir = join(process.env.HOME ?? "/tmp", "services", "hive");
  const deployExists = existsSync(join(deployDir, "package.json"));

  if (deployExists) {
    console.log(`Deploy directory exists: ${deployDir}`);
    const redeploy = await confirm("Sync latest build and config?", true);
    if (redeploy) {
      await doDeploy(deployDir);
    } else {
      console.log("  ✓ Skipped");
    }
  } else {
    console.log("Hive runs from a separate deploy directory (not this dev repo).");
    console.log(`  Dev:    ${DEV_ROOT}`);
    console.log(`  Deploy: ${deployDir}`);
    console.log("");
    const setupDeploy = await confirm("Set up the deploy directory now?", true);
    if (setupDeploy) {
      await doDeploy(deployDir);
    }
  }

  // ── 10. Service ───────────────────────────────────────────────────
  section("Service");

  const installService = await confirm("Install Hive as a LaunchAgent (starts on login)?");
  if (installService) {
    try {
      // Generate plists pointing to the deploy directory
      execFileSync("bash", ["service/install.sh"], {
        cwd: DEV_ROOT,
        stdio: "inherit",
        env: { ...process.env, HIVE_DEPLOY_DIR: deployDir },
      });
    } catch {
      console.log("  ⚠ Service installation failed — you can start manually:");
      console.log(`     cd ${deployDir} && npm start`);
    }
  }

  // ── Done ──────────────────────────────────────────────────────────
  console.log("");
  console.log("╔══════════════════════════════════════════════╗");
  console.log("║              Hive is ready!                  ║");
  console.log("╚══════════════════════════════════════════════╝");
  console.log("");
  console.log("Quick reference:");
  console.log(`  Deploy dir: ${deployDir}`);
  console.log(`  Start:      cd ${deployDir} && npm start`);
  console.log(`  Logs:       tail -f ${deployDir}/logs/hive.log`);
  console.log(`  Dev mode:   npm run dev  (from ${DEV_ROOT})`);
  console.log(`  Redeploy:   bash ${DEV_ROOT}/service/deploy.sh`);
  console.log("");
  console.log("Your chief-of-staff agent is stored in the agent_definitions collection.");
  console.log("Additional agents can be created through the chief of staff.");
  console.log("");

  rl.close();
}

// ── Section implementations ────────────────────────────────────────

async function doBusiness(hive: Record<string, any>) {
  section("Your Business");

  const businessName = await ask("Business name", hive.business?.name || "");
  const businessDesc = await ask("What does your business do? (one sentence)", hive.business?.description || "");
  const businessLocation = await ask("Location (city, state)", hive.business?.location || "");
  const businessTimezone = await ask("Timezone (e.g. America/New_York)", hive.business?.timezone || "");
  const businessHours = await ask("Business hours (e.g. 9 AM - 5 PM)", hive.business?.businessHours || "9 AM - 5 PM");
  const ownerName = await ask("Your name", hive.business?.owner?.name || "");
  const ownerRole = await ask("Your role", hive.business?.owner?.role || "CEO");

  hive.business = {
    name: businessName,
    description: businessDesc,
    ...(businessLocation ? { location: businessLocation } : {}),
    ...(businessTimezone ? { timezone: businessTimezone } : {}),
    businessHours,
    owner: { name: ownerName, role: ownerRole },
  };

  saveHiveYaml(hive);
  console.log("\n  ✓ Business info saved (hive.yaml)");
}

async function doSlack(env: Record<string, string>) {
  section("Slack App Setup");

  console.log("You need a Slack app with Socket Mode enabled.");
  console.log("");
  console.log("1. Go to: https://api.slack.com/apps");
  try {
    execFileSync("open", ["https://api.slack.com/apps"], { stdio: "pipe" });
  } catch {
    // Non-macOS or no browser — user can copy the URL
  }
  console.log('2. Click "Create New App" → "From a manifest"');
  console.log("3. Select your workspace");
  console.log("4. Choose YAML format and paste this manifest:");
  console.log("");
  console.log("─── Copy everything below this line ───");
  console.log(readFileSync(join(DEV_ROOT, "setup", "slack-manifest.yaml"), "utf-8"));
  console.log("─── Copy everything above this line ───");
  console.log("");
  console.log('5. Click "Create"');
  console.log('6. Go to "Install App" → Install to workspace');
  console.log("");

  await ask("Press Enter when your app is created and installed...");

  console.log("");
  console.log("Now collect your tokens:");
  console.log("");

  console.log('App-Level Token: Go to "Basic Information" → "App-Level Tokens"');
  console.log('  → "Generate Token and Scopes" → add scope "connections:write"');
  env.SLACK_APP_TOKEN = await ask("App-Level Token (xapp-...)", env.SLACK_APP_TOKEN || "");

  console.log("");
  console.log('Bot Token: Go to "OAuth & Permissions" → "Bot User OAuth Token"');
  env.SLACK_BOT_TOKEN = await ask("Bot Token (xoxb-...)", env.SLACK_BOT_TOKEN || "");

  console.log("");
  const wantMcp = await confirm("Do you have a Slack MCP user token (xoxp-...)? (for Slack search)", false);
  if (wantMcp) {
    env.SLACK_MCP_TOKEN = await ask("Slack MCP Token (xoxp-...)", env.SLACK_MCP_TOKEN || "");
  }

  // Validate
  if (env.SLACK_APP_TOKEN && env.SLACK_BOT_TOKEN) {
    try {
      const result = execFileSync(
        "curl",
        ["-s", "-H", `Authorization: Bearer ${env.SLACK_BOT_TOKEN}`, "https://slack.com/api/auth.test"],
        { encoding: "utf-8" },
      );
      const json = JSON.parse(result);
      if (json.ok) {
        console.log(`\n  ✓ Slack connected as: ${json.user} in ${json.team}`);
      } else {
        console.log(`\n  ⚠ Slack token test failed: ${json.error}`);
        console.log("  You can fix this in .env later.");
      }
    } catch {
      console.log("\n  ⚠ Could not validate Slack token (no network?)");
    }
  }

  saveEnv(env);

  // Also store in Keychain for honeypot-based credential flow
  try {
    if (env.SLACK_APP_TOKEN) {
      execFileSync("honeypot", ["set", "SLACK_APP_TOKEN", env.SLACK_APP_TOKEN], {
        stdio: ["pipe", "pipe", "pipe"],
      });
    }
    if (env.SLACK_BOT_TOKEN) {
      execFileSync("honeypot", ["set", "SLACK_BOT_TOKEN", env.SLACK_BOT_TOKEN], {
        stdio: ["pipe", "pipe", "pipe"],
      });
    }
  } catch {
    // honeypot may not be on PATH — .env is the primary store
  }

  console.log("  ✓ Slack tokens saved (.env)");
}

async function doAnthropic(env: Record<string, string>) {
  console.log("Get your API key from: https://console.anthropic.com/settings/keys");
  console.log("");
  env.ANTHROPIC_API_KEY = await ask("Anthropic API Key (sk-ant-...)", env.ANTHROPIC_API_KEY || "");
  saveEnv(env);

  // Also store in Keychain for honeypot-based credential flow
  try {
    if (env.ANTHROPIC_API_KEY) {
      execFileSync("honeypot", ["set", "ANTHROPIC_API_KEY", env.ANTHROPIC_API_KEY], {
        stdio: ["pipe", "pipe", "pipe"],
      });
    }
  } catch {
    // honeypot may not be on PATH (dev mode) — .env is sufficient
  }

  console.log("  ✓ Anthropic key saved (.env)");
}

async function doAgent(hive: Record<string, any>) {
  section("Chief of Staff Agent");

  console.log("Hive starts with a Chief of Staff — your primary agent.");
  console.log("Additional agents are created through it as needed.\n");

  const agentName = await ask("Name your Chief of Staff", "Mokie");

  // Store agent name in hive.yaml for template rendering
  if (!hive.agents) hive.agents = {};
  hive.agents["chief-of-staff"] = { name: agentName };
  saveHiveYaml(hive);

  // Seed chief-of-staff into agent_definitions via setup:seeds
  console.log("  Seeding agent definition...");
  execFileSync("npx", ["tsx", "setup/setup-seeds.ts"], { cwd: DEV_ROOT, stdio: "inherit" });

  console.log(`  ✓ ${agentName} (Chief of Staff) is ready`);
}

async function doConstitution(hive: Record<string, any>) {
  section("Constitution — Chief of Staff Permissions");

  const cosName = hive.agents?.["chief-of-staff"]?.name ?? "Chief of Staff";
  const ownerName = hive.business?.owner?.name ?? "you";
  const hasOtherAgents = Object.keys(hive.agents ?? {}).length > 1;

  console.log("The constitution defines what your agents can and can't do.");
  console.log(`Since ${cosName} is your only agent right now, we need to decide`);
  console.log("what permissions to grant.\n");

  // Initialize constitution config
  if (!hive.constitution) hive.constitution = {};

  // 1. Agent management
  console.log(`── Agent definitions (agent_definitions collection)`);
  console.log(`${cosName} can create new agents, edit their personality and config,`);
  console.log(`and manage the team roster.\n`);
  hive.constitution.cosCanManageAgents = true;
  console.log(`  ✓ ${cosName} can manage agent definitions\n`);

  // 2. External communications (hard gate)
  console.log(`\n── External communications (email, SMS)`);
  console.log(`This is a hard gate — when off, email and SMS tools are completely`);
  console.log(`removed from all agents. Not just a policy, they literally can't send.\n`);
  console.log(`Default: OFF. You can enable later by setting EXTERNAL_COMMS_ENABLED=true`);
  console.log(`in .env and restarting Hive.\n`);
  hive.constitution.cosCanContactExternal = await confirm(`Enable external communications now?`, false);

  // Load env to set the hard gate flag
  const extEnv = loadEnv();
  if (hive.constitution.cosCanContactExternal) {
    extEnv.EXTERNAL_COMMS_ENABLED = "true";
    console.log(`  ✓ External comms enabled — email/SMS tools available`);
    console.log(`    (sensitive topics still escalate to ${ownerName} per constitution)`);
  } else {
    extEnv.EXTERNAL_COMMS_ENABLED = "";
    console.log(`  ✗ External comms disabled — no agent can send email or SMS`);
    console.log(`    To enable later: set EXTERNAL_COMMS_ENABLED=true in .env`);
  }
  saveEnv(extEnv);

  // 3. Summary
  console.log("\n── Summary ─────────────────────────────────────");
  console.log(`  Agent management:       ✓ yes`);
  console.log(`  External communications: ${hive.constitution.cosCanContactExternal ? "✓ yes" : "✗ no"}`);
  console.log(`  Hive build & deploy:    ✗ no (external provisioning only)`);
  console.log(`  Hive source code:       ✗ no (external provisioning only)`);

  saveHiveYaml(hive);
  console.log("\n  ✓ Constitution preferences saved (hive.yaml)");
}

async function doMemory(hive: Record<string, any>, templatesDir: string) {
  const mongoUri = process.env.MONGODB_URI || "mongodb://localhost:27017";
  const mongoDb = process.env.MONGODB_DB || "hive";

  console.log("Seeding shared memory to MongoDB...");

  try {
    const client = new MongoClient(mongoUri);
    await client.connect();
    const db = client.db(mongoDb);
    const memory = db.collection("memory");

    // Ensure index
    await memory.createIndex({ path: 1 }, { unique: true });

    // Business context
    const biz = hive.business ?? {};
    const contextMd = [
      `# Business Context\n`,
      `**Company:** ${biz.name ?? ""}`,
      `**About:** ${biz.description ?? ""}`,
      biz.location ? `**Location:** ${biz.location}` : "",
      biz.timezone ? `**Timezone:** ${biz.timezone}` : "",
      biz.businessHours ? `**Business Hours:** ${biz.businessHours}${biz.timezone ? ` (${biz.timezone})` : ""}` : "",
      `**Owner:** ${biz.owner?.name ?? ""} (${biz.owner?.role ?? ""})`,
      "",
      "## Additional Context",
      "(Add more details about your business here — products, services, team, etc.)",
    ]
      .filter(Boolean)
      .join("\n");

    await memory.updateOne(
      { path: "shared/business-context.md" },
      { $set: { content: contextMd, updatedAt: new Date(), updatedBy: "setup-wizard" } },
      { upsert: true },
    );
    console.log("  ✓ shared/business-context.md");

    // Constitution
    const constitutionTplPath = join(templatesDir, "constitution.md.tpl");
    if (existsSync(constitutionTplPath)) {
      const constitutionTpl = readFileSync(constitutionTplPath, "utf-8");

      const team: Record<string, string> = {};
      for (const [id, def] of Object.entries(hive.agents ?? {})) {
        team[id] = (def as any).name ?? id;
      }

      const constitutionCtx = { business: biz, team };
      const content = renderTemplate(constitutionTpl, constitutionCtx);

      await memory.updateOne(
        { path: "shared/constitution.md" },
        { $set: { content, updatedAt: new Date(), updatedBy: "setup-wizard" } },
        { upsert: true },
      );
      console.log("  ✓ shared/constitution.md");
    }

    await client.close();
    console.log("  ✓ Memory seeded to MongoDB");
  } catch (err) {
    console.log(`  ⚠ Failed to seed memory: ${err}`);
    console.log("  Make sure MongoDB is running (brew services start mongodb-community)");
  }
}

async function doBuild() {
  console.log("  Compiling TypeScript...");
  try {
    execFileSync("npm", ["run", "build"], { cwd: DEV_ROOT, stdio: "pipe" });
    console.log("  ✓ Build complete");
  } catch (err) {
    console.log("  ⚠ Build failed:");
    console.log(String(err));
  }
}

async function doDeploy(deployDir: string) {
  const { mkdirSync: mkdir } = await import("node:fs");

  if (!existsSync(join(deployDir, "package.json"))) {
    // Fresh clone
    console.log("  Cloning repository...");
    const parentDir = resolve(deployDir, "..");
    mkdir(parentDir, { recursive: true });

    const remoteUrl = execFileSync("git", ["remote", "get-url", "origin"], { cwd: DEV_ROOT, encoding: "utf-8" }).trim();
    execFileSync("git", ["clone", remoteUrl, deployDir], { stdio: "inherit" });
    console.log("  ✓ Repository cloned");
  } else {
    // Pull latest
    console.log("  Pulling latest...");
    try {
      execFileSync("git", ["pull", "--ff-only"], { cwd: deployDir, stdio: "inherit" });
    } catch {
      console.log("  ⚠ git pull failed — continuing with existing code");
    }
  }

  // Install production dependencies
  console.log("  Installing production dependencies...");
  execFileSync("npm", ["install", "--omit=dev"], { cwd: deployDir, stdio: "pipe" });
  console.log("  ✓ Dependencies installed");

  // Copy instance-specific files (not in git)
  console.log("  Syncing config and build output...");

  // .env
  const envSrc = join(DEV_ROOT, ".env");
  if (existsSync(envSrc)) {
    const { copyFileSync } = await import("node:fs");
    copyFileSync(envSrc, join(deployDir, ".env"));
    console.log("  ✓ .env");
  }

  // hive.yaml
  const hiveSrc = join(DEV_ROOT, "hive.yaml");
  if (existsSync(hiveSrc)) {
    const { copyFileSync } = await import("node:fs");
    copyFileSync(hiveSrc, join(deployDir, "hive.yaml"));
    console.log("  ✓ hive.yaml");
  }

  // dist/ (build output)
  const distSrc = join(DEV_ROOT, "dist");
  if (existsSync(distSrc)) {
    execFileSync("rsync", ["-a", "--delete", `${distSrc}/`, `${join(deployDir, "dist")}/`], { stdio: "pipe" });
    console.log("  ✓ dist/");
  }

  // Ensure logs directory
  mkdir(join(deployDir, "logs"), { recursive: true });

  console.log(`\n  ✓ Deploy directory ready: ${deployDir}`);
}

// Backward compat — run directly if executed as main
const isMain = import.meta.url === `file://${process.argv[1]}`;
if (isMain) {
  runWizard().catch((err) => {
    console.error("Setup failed:", err);
    rl.close();
    process.exit(1);
  });
}
