#!/usr/bin/env npx tsx
/**
 * Hive Setup Wizard — interactive CLI to configure a new Hive instance.
 *
 * Saves progress after each section so you can quit and resume.
 * On resume, completed sections are detected and skipped (with option to redo).
 *
 * Usage:
 *   npm run setup
 *   npx tsx setup/setup-wizard.ts
 */

import { createInterface } from "node:readline";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { execSync } from "node:child_process";
import { resolve, join } from "node:path";
import { stringify as toYaml, parse as parseYaml } from "yaml";
import { MongoClient } from "mongodb";

const ROOT = resolve(import.meta.dirname, "..");
const ENV_PATH = join(ROOT, ".env");
const HIVE_YAML_PATH = join(ROOT, "hive.yaml");

const rl = createInterface({ input: process.stdin, output: process.stdout });

function ask(question: string, defaultVal = ""): Promise<string> {
  const prompt = defaultVal ? `${question} [${defaultVal}]: ` : `${question}: `;
  return new Promise((resolve) => {
    rl.question(prompt, (answer) => {
      resolve(answer.trim() || defaultVal);
    });
  });
}

async function confirm(question: string, defaultYes = true): Promise<boolean> {
  const hint = defaultYes ? "Y/n" : "y/N";
  const answer = await ask(`${question} (${hint})`, defaultYes ? "y" : "n");
  return answer.toLowerCase().startsWith("y");
}

function banner() {
  console.log("");
  console.log("╔══════════════════════════════════════════════╗");
  console.log("║            Hive Setup Wizard                 ║");
  console.log("║   Multi-Agent Slack Orchestration Framework  ║");
  console.log("╚══════════════════════════════════════════════╝");
  console.log("");
}

function section(title: string) {
  console.log("");
  console.log(`── ${title} ${"─".repeat(Math.max(0, 44 - title.length))}`);
  console.log("");
}

// ── Env file helpers ───────────────────────────────────────────────

function loadEnv(): Record<string, string> {
  if (!existsSync(ENV_PATH)) return {};
  const env: Record<string, string> = {};
  for (const line of readFileSync(ENV_PATH, "utf-8").split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq);
    const val = trimmed.slice(eq + 1);
    env[key] = val;
  }
  return env;
}

function saveEnv(env: Record<string, string>) {
  const lines: string[] = [
    "# Hive environment — generated by setup wizard",
    "# Secrets and API keys. Do not commit this file.",
    "",
  ];

  const groups: Array<{ header: string; keys: string[] }> = [
    { header: "# Slack", keys: ["SLACK_APP_TOKEN", "SLACK_BOT_TOKEN", "SLACK_MCP_TOKEN"] },
    { header: "# Anthropic", keys: ["ANTHROPIC_API_KEY"] },
    { header: "# SMS (Quo/OpenPhone)", keys: ["QUO_API_KEY", "QUO_PHONE_NUMBER_ID"] },
    { header: "# Google", keys: ["GOOGLE_ACCOUNT"] },
    { header: "# Project Management", keys: ["LINEAR_API_KEY", "CLICKUP_API_TOKEN"] },
  ];

  const written = new Set<string>();
  for (const group of groups) {
    const groupLines: string[] = [];
    for (const key of group.keys) {
      written.add(key);
      const val = env[key];
      if (val) {
        groupLines.push(`${key}=${val}`);
      } else {
        groupLines.push(`# ${key}=`);
      }
    }
    if (groupLines.some((l) => !l.startsWith("#"))) {
      lines.push(group.header);
      lines.push(...groupLines);
      lines.push("");
    }
  }

  // Write any extra keys not in the groups
  for (const [key, val] of Object.entries(env)) {
    if (!written.has(key) && val) {
      lines.push(`${key}=${val}`);
    }
  }

  writeFileSync(ENV_PATH, lines.join("\n") + "\n");
}

// ── Hive yaml helpers ──────────────────────────────────────────────

function loadHiveYaml(): Record<string, any> {
  if (!existsSync(HIVE_YAML_PATH)) return {};
  return parseYaml(readFileSync(HIVE_YAML_PATH, "utf-8")) ?? {};
}

function saveHiveYaml(config: Record<string, any>) {
  writeFileSync(HIVE_YAML_PATH, toYaml(config));
}

// ── Section detection ──────────────────────────────────────────────

function isBusinessDone(hive: Record<string, any>): boolean {
  return !!(hive.business?.name && hive.business?.owner?.name);
}

function isSlackDone(env: Record<string, string>): boolean {
  return !!(env.SLACK_APP_TOKEN && env.SLACK_BOT_TOKEN);
}

function isAgentDone(): boolean {
  return existsSync(join(ROOT, "agents", "chief-of-staff", "agent.yaml"));
}

function isBuildDone(): boolean {
  return existsSync(join(ROOT, "dist", "index.js"));
}

// ── Main ───────────────────────────────────────────────────────────

async function main() {
  banner();

  const env = loadEnv();
  const hive = loadHiveYaml();

  // Check for resumed session
  const completedSections: string[] = [];
  if (isBusinessDone(hive)) completedSections.push("Business info");
  if (isSlackDone(env)) completedSections.push("Slack");
  if (isAgentDone()) completedSections.push("Agent setup");
  if (isBuildDone()) completedSections.push("Build");

  if (completedSections.length > 0) {
    console.log("Resuming setup. Already completed:");
    for (const s of completedSections) {
      console.log(`  ✓ ${s}`);
    }
    console.log("");
  } else {
    console.log("This wizard will configure Hive for your business.");
    console.log("Progress is saved after each section — you can quit and resume anytime.");
    console.log("");
    await ask("Press Enter to begin...");
  }

  // ── 1. Business Info ──────────────────────────────────────────────
  if (isBusinessDone(hive)) {
    console.log(`Business: ${hive.business.name} (${hive.business.owner.name}, ${hive.business.owner.role})`);
    const redo = await confirm("Redo business info?", false);
    if (!redo) {
      console.log("  ✓ Skipped");
    } else {
      await doBusiness(hive);
    }
  } else {
    await doBusiness(hive);
  }

  // ── 2. Slack ──────────────────────────────────────────────────────
  if (isSlackDone(env)) {
    console.log(`Slack: ✓ tokens configured`);
    const redo = await confirm("Redo Slack setup?", false);
    if (!redo) {
      console.log("  ✓ Skipped");
    } else {
      await doSlack(env);
    }
  } else {
    await doSlack(env);
  }

  // ── 3. Anthropic ──────────────────────────────────────────────────
  section("Anthropic");

  if (env.ANTHROPIC_API_KEY) {
    console.log("Anthropic API key: ✓ configured");
    const redo = await confirm("Change it?", false);
    if (redo) {
      await doAnthropic(env);
    } else {
      console.log("  ✓ Skipped");
    }
  } else {
    console.log("Your Claude CLI session is already authenticated — Hive's Agent SDK");
    console.log("will use that automatically. No API key needed.");
    console.log("");
    const wantKey = await confirm("Use a separate API key instead?", false);
    if (wantKey) {
      await doAnthropic(env);
    } else {
      console.log("  ✓ Using existing Claude authentication");
      saveEnv(env);
    }
  }

  // ── 4. Optional Integrations ──────────────────────────────────────
  section("Optional Integrations");

  console.log("These can be added later. Press Enter to skip any.\n");

  // SMS via Quo
  const wantQuo = await confirm("Enable SMS via Quo (OpenPhone)?", false);
  if (wantQuo) {
    console.log("Get your API key from: Quo workspace settings → API tab");
    env.QUO_API_KEY = await ask("Quo API Key", env.QUO_API_KEY || "");
    env.QUO_PHONE_NUMBER_ID = await ask("Default Phone Number ID (PNxxx)", env.QUO_PHONE_NUMBER_ID || "");

    const smsLines: Array<{ id: string; label: string; number: string; slackChannel: string }> = [];
    const quoLines: Record<string, { id: string; number: string; label: string }> = {};

    const addLines = await confirm("Configure named phone lines?", false);
    if (addLines) {
      let more = true;
      while (more) {
        const lineName = await ask("Line name (e.g. main, personal)");
        const lineId = await ask("Phone Number ID (PNxxx)");
        const lineNumber = await ask("Phone number (e.g. (555) 123-4567)");
        const lineLabel = await ask("Label (e.g. Jane's Line)");
        const lineChannel = await ask("Slack channel for incoming SMS", `sms-${lineName}`);

        quoLines[lineName] = { id: lineId, number: lineNumber, label: lineLabel };
        smsLines.push({ id: lineId, label: lineLabel, number: lineNumber, slackChannel: lineChannel });

        more = await confirm("Add another line?", false);
      }
    }

    if (smsLines.length > 0) hive.sms = { lines: smsLines };
    if (Object.keys(quoLines).length > 0) hive.quo = { lines: quoLines };
  }

  // Google
  const wantGoogle = await confirm("Enable Google Gmail/Calendar integration?", false);
  if (wantGoogle) {
    env.GOOGLE_ACCOUNT = await ask("Google account email", env.GOOGLE_ACCOUNT || "");
    console.log("  Note: You'll need the 'gog' CLI installed and authenticated.");
  }

  // Project Management
  const wantPm = await confirm("Enable project management integration?", false);
  if (wantPm) {
    const pmChoice = await ask("Which system? (linear / clickup)", "");
    if (pmChoice.toLowerCase().startsWith("l")) {
      env.LINEAR_API_KEY = await ask("Linear API Key", env.LINEAR_API_KEY || "");
      console.log("  Get it from: Linear → Settings → API → Personal API Keys");
    } else if (pmChoice.toLowerCase().startsWith("c")) {
      env.CLICKUP_API_TOKEN = await ask("ClickUp API Token", env.CLICKUP_API_TOKEN || "");
      console.log("  Get it from: ClickUp → Settings → Apps → API Token");
    } else {
      console.log("  Skipped — you can configure this in .env later.");
    }
  }

  // Save after integrations
  saveEnv(env);
  saveHiveYaml(hive);
  console.log("\n  ✓ Configuration saved (.env + hive.yaml)");

  // ── 5. Agent Setup ────────────────────────────────────────────────
  if (isAgentDone()) {
    console.log("\nChief of Staff agent: ✓ already set up");
    const redo = await confirm("Regenerate agent from template?", false);
    if (redo) {
      await doAgent(hive);
    } else {
      console.log("  ✓ Skipped");
    }
  } else {
    await doAgent(hive);
  }

  // ── 6. Seed Memory to MongoDB ─────────────────────────────────────
  section("Memory (MongoDB)");
  await doMemory(hive);

  // ── 7. Build ──────────────────────────────────────────────────────
  section("Build");

  if (isBuildDone()) {
    console.log("Build output exists.");
    const rebuild = await confirm("Rebuild?", true);
    if (!rebuild) {
      console.log("  ✓ Skipped");
    } else {
      await doBuild();
    }
  } else {
    await doBuild();
  }

  // ── 8. Service ────────────────────────────────────────────────────
  section("Service");

  const installService = await confirm("Install Hive as a LaunchAgent (starts on login)?");
  if (installService) {
    try {
      execSync("bash service/install.sh", { cwd: ROOT, stdio: "inherit" });
    } catch {
      console.log("  ⚠ Service installation failed — you can run manually with 'npm start'");
    }
  }

  // ── Done ──────────────────────────────────────────────────────────
  console.log("");
  console.log("╔══════════════════════════════════════════════╗");
  console.log("║              Hive is ready!                  ║");
  console.log("╚══════════════════════════════════════════════╝");
  console.log("");
  console.log("Quick reference:");
  console.log("  Start:    npm start");
  console.log("  Dev mode: npm run dev");
  console.log("  Logs:     tail -f logs/hive.log");
  console.log("  Update:   npm run update");
  console.log("");
  console.log("Your chief-of-staff agent is in agents/chief-of-staff/.");
  console.log("Additional agents can be created through the chief of staff.");
  console.log("");

  rl.close();
}

// ── Section implementations ────────────────────────────────────────

async function doBusiness(hive: Record<string, any>) {
  section("Your Business");

  const businessName = await ask("Business name", hive.business?.name || "");
  const businessDesc = await ask("What does your business do? (one sentence)", hive.business?.description || "");
  const businessLocation = await ask("Location (city, state)", hive.business?.location || "");
  const ownerName = await ask("Your name", hive.business?.owner?.name || "");
  const ownerRole = await ask("Your role", hive.business?.owner?.role || "CEO");

  hive.business = {
    name: businessName,
    description: businessDesc,
    ...(businessLocation ? { location: businessLocation } : {}),
    owner: { name: ownerName, role: ownerRole },
  };

  saveHiveYaml(hive);
  console.log("\n  ✓ Business info saved (hive.yaml)");
}

async function doSlack(env: Record<string, string>) {
  section("Slack App Setup");

  console.log("You need a Slack app with Socket Mode enabled.");
  console.log("");
  console.log("1. Go to: https://api.slack.com/apps");
  console.log('2. Click "Create New App" → "From a manifest"');
  console.log("3. Select your workspace");
  console.log("4. Choose YAML format and paste this manifest:");
  console.log("");
  console.log("─── Copy everything below this line ───");
  console.log(readFileSync(join(ROOT, "setup", "slack-manifest.yaml"), "utf-8"));
  console.log("─── Copy everything above this line ───");
  console.log("");
  console.log('5. Click "Create"');
  console.log('6. Go to "Install App" → Install to workspace');
  console.log("");

  await ask("Press Enter when your app is created and installed...");

  console.log("");
  console.log("Now collect your tokens:");
  console.log("");

  console.log('App-Level Token: Go to "Basic Information" → "App-Level Tokens"');
  console.log('  → "Generate Token and Scopes" → add scope "connections:write"');
  env.SLACK_APP_TOKEN = await ask("App-Level Token (xapp-...)", env.SLACK_APP_TOKEN || "");

  console.log("");
  console.log('Bot Token: Go to "OAuth & Permissions" → "Bot User OAuth Token"');
  env.SLACK_BOT_TOKEN = await ask("Bot Token (xoxb-...)", env.SLACK_BOT_TOKEN || "");

  console.log("");
  const wantMcp = await confirm("Do you have a Slack MCP user token (xoxp-...)? (for Slack search)", false);
  if (wantMcp) {
    env.SLACK_MCP_TOKEN = await ask("Slack MCP Token (xoxp-...)", env.SLACK_MCP_TOKEN || "");
  }

  // Validate
  if (env.SLACK_APP_TOKEN && env.SLACK_BOT_TOKEN) {
    try {
      const result = execSync(
        `curl -s -H "Authorization: Bearer ${env.SLACK_BOT_TOKEN}" https://slack.com/api/auth.test`,
        { encoding: "utf-8" },
      );
      const json = JSON.parse(result);
      if (json.ok) {
        console.log(`\n  ✓ Slack connected as: ${json.user} in ${json.team}`);
      } else {
        console.log(`\n  ⚠ Slack token test failed: ${json.error}`);
        console.log("  You can fix this in .env later.");
      }
    } catch {
      console.log("\n  ⚠ Could not validate Slack token (no network?)");
    }
  }

  saveEnv(env);
  console.log("  ✓ Slack tokens saved (.env)");
}

async function doAnthropic(env: Record<string, string>) {
  console.log("Get your API key from: https://console.anthropic.com/settings/keys");
  console.log("");
  env.ANTHROPIC_API_KEY = await ask("Anthropic API Key (sk-ant-...)", env.ANTHROPIC_API_KEY || "");
  saveEnv(env);
  console.log("  ✓ Anthropic key saved (.env)");
}

async function doAgent(hive: Record<string, any>) {
  section("Chief of Staff Agent");

  console.log("Hive starts with a Chief of Staff — your primary agent.");
  console.log("Additional agents are created through it as needed.\n");

  const agentName = await ask("Name your Chief of Staff", "Mokie");

  // Store agent name in hive.yaml for template rendering
  if (!hive.agents) hive.agents = {};
  hive.agents["chief-of-staff"] = { name: agentName };
  saveHiveYaml(hive);

  // Generate only chief-of-staff from templates
  console.log("  Generating agent from template...");
  execSync("npx tsx setup/generate-agents.ts", { cwd: ROOT, stdio: "inherit" });

  // Remove any other agents that got generated
  const { readdirSync, rmSync } = await import("node:fs");
  const agentsDir = join(ROOT, "agents");
  if (existsSync(agentsDir)) {
    for (const dir of readdirSync(agentsDir)) {
      if (dir !== "chief-of-staff") {
        rmSync(join(agentsDir, dir), { recursive: true, force: true });
      }
    }
  }

  console.log(`  ✓ ${agentName} (Chief of Staff) is ready`);
}

async function doMemory(hive: Record<string, any>) {
  const mongoUri = process.env.MONGODB_URI || "mongodb://localhost:27017";
  const mongoDb = process.env.MONGODB_DB || "hive";

  console.log("Seeding shared memory to MongoDB...");

  try {
    const client = new MongoClient(mongoUri);
    await client.connect();
    const db = client.db(mongoDb);
    const memory = db.collection("memory");

    // Ensure index
    await memory.createIndex({ path: 1 }, { unique: true });

    // Business context
    const biz = hive.business ?? {};
    const contextMd = [
      `# Business Context\n`,
      `**Company:** ${biz.name ?? ""}`,
      `**About:** ${biz.description ?? ""}`,
      biz.location ? `**Location:** ${biz.location}` : "",
      `**Owner:** ${biz.owner?.name ?? ""} (${biz.owner?.role ?? ""})`,
      "",
      "## Additional Context",
      "(Add more details about your business here — products, services, team, etc.)",
    ]
      .filter(Boolean)
      .join("\n");

    await memory.updateOne(
      { path: "shared/business-context.md" },
      { $set: { content: contextMd, updatedAt: new Date(), updatedBy: "setup-wizard" } },
      { upsert: true },
    );
    console.log("  ✓ shared/business-context.md");

    // Constitution
    const constitutionTplPath = join(ROOT, "setup", "templates", "constitution.md.tpl");
    if (existsSync(constitutionTplPath)) {
      const { render: renderTemplate } = await import("./template-renderer.ts");
      const constitutionTpl = readFileSync(constitutionTplPath, "utf-8");

      const team: Record<string, string> = {};
      for (const [id, def] of Object.entries(hive.agents ?? {})) {
        team[id] = (def as any).name ?? id;
      }

      const constitutionCtx = { business: biz, team };
      const content = renderTemplate(constitutionTpl, constitutionCtx);

      await memory.updateOne(
        { path: "shared/constitution.md" },
        { $set: { content, updatedAt: new Date(), updatedBy: "setup-wizard" } },
        { upsert: true },
      );
      console.log("  ✓ shared/constitution.md");
    }

    await client.close();
    console.log("  ✓ Memory seeded to MongoDB");
  } catch (err) {
    console.log(`  ⚠ Failed to seed memory: ${err}`);
    console.log("  Make sure MongoDB is running (brew services start mongodb-community)");
  }
}

async function doBuild() {
  console.log("  Compiling TypeScript...");
  try {
    execSync("npm run build", { cwd: ROOT, stdio: "pipe" });
    console.log("  ✓ Build complete");
  } catch (err) {
    console.log("  ⚠ Build failed:");
    console.log(String(err));
  }
}

main().catch((err) => {
  console.error("Setup failed:", err);
  rl.close();
  process.exit(1);
});
